### ISSUE TITLE
Project Process and Task List

### ISSUE THREAD

**Issue by SampathTharanga** [SampathTharanga/DSR-System-V1.0#1]
- [x] Draw the flow chart
- [x] Draw the ER
- [x] Design UI
- [x] Complete the Login an SignUp function
- [x] Complete the Item function
- [x] Complete the Load function
- [x] Complete the Unload function
- [ ] Complete the Report function
- [x] Complete the Chart function
- [ ] Complete the About function
- [ ] Relese the Setup file DSR System V 1.0
